pages:
  image: registry.plmlab.math.cnrs.fr/docker-images/ubuntu/21.10:base
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y git curl wget && apt-get install -y julia
    - julia --project -e 'using Pkg; Pkg.activate("."); Pkg.instantiate()'
    - julia --project -e 'using Pkg; pkg"dev PencilArrays"; pkg"dev WriteVTK"'
    - julia --project -e 'using Pkg; import SuperFluids; Pkg.add("Documenter")'
    - julia --project --color=yes docs/make.jl
    - mv docs/build public
  artifacts:
    paths:
      - public
#  only:
#    - master
